services:
  postgres:
    container_name: lp-postgres
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lucky_purchase
    ports:
      - "11111:11111"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: -p 11111
  api:
    build: ./api
    container_name: lp-api
    ports:
      - "7777:7777"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin@lp-postgres:11111/lucky_purchase"
      PORT: 7777
    volumes:
      - ./api/static:/app/static
    restart: always

  web:
    build:
      context: ./web
      args:
        - NEXT_PUBLIC_API_BASE_URL=https://lp-api.fly0utwest.dev
        - NEXT_PUBLIC_STATIC_URL=https://lp-api.fly0utwest.dev/static/
    container_name: lp-web
    ports:
      - "10000:10000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_BASE_URL: "https://lp-api.fly0utwest.dev"
      NEXT_PUBLIC_STATIC_URL: "https://lp-api.fly0utwest.dev/static/"
    volumes:
      - ./api/static:/app/static
    restart: always
volumes:
  pgdata:
  pgadmin-data:


