services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lucky_purchase
    ports:
      - "11111:11111"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./api
    container_name: lp-api
    ports:
      - "7777:7777"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:11111/lucky_purchase"
      PORT: 7777
    volumes:
      - ./api/static:/app/static
    restart: always

  web:
    build: ./web
    container_name: lp-web
    ports:
      - "10000:10000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:10000"
      NEXT_PUBLIC_STATIC_URL: "http://localhost:10000/static/"
    volumes:
      - ./api/static:/app/static
    restart: always

volumes:
  pgdata:
  pgadmin-data:

