services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lucky_purchase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./api
    container_name: lp-api
    ports:
      - "7777:7777"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/lucky_purchase"
      PORT: 7777
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always

  caddy:
    image: caddy:latest
    ports:
      - "5555:5555"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./static:/srv/static

volumes:
  pgdata:
  pgadmin-data:
  caddy_data:
  caddy_config:
